stages:
  download:
    cmd: python src/create_dataset.py
    deps:
    - src/create_dataset.py
    outs:
    - data/raw
  featurization:
    cmd: python src/featurization.py
    deps:
    - data/raw
    - src/featurization.py
    params:
    - featurization.seed
    outs:
    - data/features
  trainpredict:
    cmd: python src/train_predict.py
    deps:
    - data/features
    - src/train_predict.py
    params:
    - trainpredict.seed
    - trainpredict.trials
    outs:
    - data/models
    - data/subs
  evaluation:
    cmd: python src/evaluate.py
    deps:
    - data/features
    - src/evaluate.py
    params:
    - evaluation.model_index
    - evaluation.collection_index
    - evaluation.n_est
    - evaluation.cbt
    - evaluation.ss
    metrics:
    - data/scores.json:
        cache: false
    plots:
    - data/prc.json:
        cache: false
        x: recall
        y: precision
    - data/roc.json:
        cache: false
        x: fpr
        y: tpr
